---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/002_total_population-ea-cart/002_total_population-ea-cart.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/164985/articles/203427/master/file/figures/002_total_population-ea-cart/002_total_population-ea-cart.png"
