---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/FulaLocalAncestryDeviationsFig24panels/FulaLocalAncestryDeviationsFig24panels.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/164985/articles/203427/master/folder/figures/FulaLocalAncestryDeviationsFig24panels"
    url: "/users/164985/articles/203427/master/file/figures/FulaLocalAncestryDeviationsFig24panels/FulaLocalAncestryDeviationsFig24panels.png"
