---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/FULAILRTmanhattanIII/FULAILRTmanhattanIII.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/164985/articles/203427/master/file/figures/FULAILRTmanhattanIII/FULAILRTmanhattanIII.png"
    folder_url: "/users/164985/articles/203427/master/folder/figures/FULAILRTmanhattanIII"
